name: Sincronizar Bascula Xiaomi a Intervals

on:
  schedule:
    - cron: '0 7 * * *' # Se ejecutará solo de forma automática todas las mañanas a las 7:00 AM
  workflow_dispatch:   # <--- ESTO ACTIVA EL BOTÓN MANUAL EN TU IPHONE

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el exportador
        uses: actions/checkout@v3
        with:
          repository: 'lswiderski/mi-scale-exporter'

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar transferencia de peso
        env:
          MISCALE_USER: ${{ secrets.XIAOMI_USER }}
          MISCALE_PASSWORD: ${{ secrets.XIAOMI_PASSWORD }}
          INTERVALS_API_KEY: ${{ secrets.INTERVALS_API_KEY }}
          INTERVALS_ATHLETE_ID: ${{ secrets.INTERVALS_ATHLETE_ID }}
        run: npm start
